notifications:
  webhooks:
    - https://webhook.commit-email.info/

rvm:
  - 2.4
  - 2.5
  - 2.6

dist: xenial

addons:
  apt:
    update: true
    packages:
      - libreoffice

before_install:
  - ln -s Gemfile.local{.example,}

script:
  - bin/rails test
