name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.6"
          - "2.7"
          - "3.0"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies to build gems
        run: |
          sudo apt update
          sudo apt install -y -V libreoffice
          ln -s Gemfile.local{.example,}
      - name: Install dependency gems
        run: |
          bundle install
      - name: Install dependency Node.js modules
        run: |
          PATH=$PWD/bin:$PATH rails yarn:install
      - name: Test
        run: |
          PATH=$PWD/bin:$PATH rails test
